site_name: wiki.joeir.net
site_url: http://wiki.joeir.net
repo_url: https://github.com/zephinzer/net.joeir.wiki.
site_author: zephinzer
site_description: my wiki of sorts
nav:
  - Home: ./index.md
  - Code Logistics:
    - Git 101: ./code-logistics/git.md
  - Wing Chun:
    - Forms: ./wing-chun/forms.md
  - Español:
    - Los Numeros y Recuento: ./español/los-numeros-y-recuento.md
    - Los Países y Las Nacionalidades: ./español/los-países-y-las-nacionalidades.md
    - Las Referencias de Aprender: ./español/las-referencias-de-aprender.md
    - El Tiempo: ./español/el-tiempo.md
    - Los Verbos: ./español/los-verbos.md
theme: mkdocs
markdown_extensions:
  - admonition