# enlace de referencia: https://www.mkdocs.org/user-guide/configuration/
site_name: wiki.joeir.net
site_url: http://wiki.joeir.net
repo_url: https://gitlab.com/zephinzer/net.joeir.wiki
site_author: zephinzer
site_description: Joseph's Wiki of Sorts
google_analytics:
  - UA-142320208-2
  - wiki.joeir.net
nav:
  - Home: ./index.md
  - DevOps:
    - Continuous Integration: ./devops/continuous-integration.md
    - Versioning: ./devops/versioning.md
    - Tools:
      - Git: ./devops/tools/git.md
      - Kubernetes: ./tools/tools/kubernetes.md
      - Shell: ./devops/tools/shell.md
  - Wing Chun:
    - Forms:
      - Siu Lim Tau: ./wing-chun/forms.md
  - Español:
    - Numeros y Recuento: ./español/numeros-y-recuento.md
    - Países y Nacionalidades: ./español/países-y-nacionalidades.md
    - Referencias de Aprender: ./español/referencias-de-aprender.md
    - El Tiempo: ./español/el-tiempo.md
    - Verbos: ./español/verbos.md
    - Vocabulario: ./español/vocabulario.md
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - sh
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
dev_addr: 0.0.0.0:12345
