# enlace de referencia: https://www.mkdocs.org/user-guide/configuration/
site_name: wiki.joeir.net
site_url: http://wiki.joeir.net
repo_url: https://gitlab.com/zephinzer/net.joeir.wiki
site_author: zephinzer
site_description: Joseph's Wiki of Sorts
google_analytics:
  - UA-142320208-2
  - wiki.joeir.net
nav:
  - Home: ./index.md
  - Software Development:
    - Git: ./dev/git.md
    - Golang: ./dev/golang.md
    - Kubernetes: ./dev/kubernetes.md
    - Node: ./dev/node.md
    - Public Key Infrastructure: ./dev/pki.md
  - Organization Development:
    - Psychological Safety: ./od/psychological-safety.md
    - Interpersonal: ./od/interpersonal.md
    - Intrapersonal: ./od/intrapersonal.md
  - Wing Chun: ./wingchun/index.md
  - Bahasa:
    - Angka: ./bahasa/angka.md
  - Español:
    - Numeros y Recuento: ./español/numeros-y-recuento.md
    - Países y Nacionalidades: ./español/países-y-nacionalidades.md
    - Referencias de Aprender: ./español/referencias-de-aprender.md
    - El Tiempo: ./español/el-tiempo.md
    - Verbos: ./español/verbos.md
    - Vocabulario: ./español/vocabulario.md
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - sh
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
dev_addr: 0.0.0.0:12345
