# enlace de referencia: https://www.mkdocs.org/user-guide/configuration/
site_name: wiki.joeir.net
site_url: http://wiki.joeir.net
repo_url: https://github.com/zephinzer/net.joeir.wiki.
repo_name: GitHub
site_author: zephinzer
site_description: Joseph's Wiki of Sorts
google_analytics:
  - UA-142320208-2
  - wiki.joeir.net
nav:
  - Home: ./index.md
  - Organisational Development:
    - Overview: ./todo.md
    - Intrapersonal: ./todo.md
    - Interpersonal: ./todo.md
    - Groups: ./todo.md
    - Systems: ./todo.md
  - Software Engineering:
    - Overview: ./todo.md
    - Product Team Roles:
      - Developer: ./todo.md
      - Operations: ./todo.md
      - Quality Engineer: ./todo.md
      - UX Designer: ./todo.md
      - Scrum Master: ./todo.md
      - Product Manager: ./todo.md
      - Product Owner: ./todo.md
    - Paradigms:
      - Functional: ./todo.md
      - Object Oriented: ./todo.md
    - Development:
      - Architecture:
        - Monolith: ./todo.md
        - Service Oriented: ./todo.md
        - Microservices: ./todo.md
        - Serverless: ./todo.md
      - Naming Things: ./todo.md
      - Testing: ./todo.md
    - DevOps:
      - Continuous Integration: ./todo.md
      - Continuous Delivery: ./todo.md
      - Environmnt Provisioning: ./todo.md
      - Package Management: ./todo.md
    - Operations:
      - Infrastructure Provisioning: ./todo.md
      - System Observability: ./todo.md
    - Software Guides:
      - Git: ./tools/git.md
      - Kubernetes: ./tools/kubernetes.md
  - Wing Chun:
    - Forms:
      - Siu Lim Tau: ./wing-chun/forms.md
  - Español:
    - Los Numeros y Recuento: ./español/los-numeros-y-recuento.md
    - Los Países y Las Nacionalidades: ./español/los-países-y-las-nacionalidades.md
    - Las Referencias de Aprender: ./español/las-referencias-de-aprender.md
    - El Tiempo: ./español/el-tiempo.md
    - Los Verbos: ./español/los-verbos.md
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - sh
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
dev_addr: 0.0.0.0:12345
