# enlace de referencia: https://www.mkdocs.org/user-guide/configuration/
site_name: wiki.joeir.net
site_url: http://wiki.joeir.net
repo_url: https://gitlab.com/zephinzer/wiki.joeir.net
site_author: zephinzer
site_description: Joseph's Wiki of Sorts
google_analytics:
  - UA-142320208-2
  - wiki.joeir.net
nav:
  - Home: ./index.md
  - Software Engineering:
    - Concepts:
      - Cloud-Native: ./software-engineering/concepts/cloud-native.md
    - Languages & Runtimes:
      - Golang: ./software-engineering/languages-runtimes/golang.md
      - Node: ./software-engineering/languages-runtimes/node.md
    - Tools:
      - Git: ./software-engineering/tools/git.md
      - Docker: ./software-engineering/tools/docker.md
      - Kubernetes: ./software-engineering/tools/kubernetes.md
    - Operating Systems:
      - Ubuntu: ./software-engineering/os/ubuntu.md
    - System Administration:
      - Public Key Infrastructure: ./software-engineering/sysadmin/pki.md
  - OD/Coaching/Counselling:
    - Interpersonal: ./od/interpersonal.md
    - Intrapersonal: ./od/intrapersonal.md
    - Psychological Safety: ./od/psychological-safety.md
  - Wing Chun: ./wingchun/index.md
  - Bahasa:
    - Angka: ./bahasa/angka.md
    - Warna: ./bahasa/warna.md
  - Español:
    - El Tiempo: ./español/el-tiempo.md
    - La Familia: ./español/la-familia.md
    - Numeros y Recuento: ./español/numeros-y-recuento.md
    - Países y Nacionalidades: ./español/países-y-nacionalidades.md
    - Referencias de Aprender: ./español/referencias-de-aprender.md
    - Verbos: ./español/verbos.md
    - Vocabulario: ./español/vocabulario.md
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - sh
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
dev_addr: 0.0.0.0:12345
