# enlace de referencia: https://www.mkdocs.org/user-guide/configuration/
site_name: wiki.joeir.net
site_url: http://wiki.joeir.net
repo_url: https://gitlab.com/zephinzer/wiki.joeir.net
site_author: zephinzer
site_description: Joseph's Wiki of Sorts
google_analytics:
  - UA-142320208-2
  - wiki.joeir.net
nav:
  - Home: ./index.md
  - Code:
      - Career and Organisation:
          - Comptency Frameworks: ./code/career-and-organisation/competency-frameworks.md
      - Concepts:
          - Cloud-Native: ./cloud-native.md
      - Software-as-a-Service:
          - Wordpress: ./wordpress.md
      - Databases:
          - MySQL: ./mysql.md
      - Software Engineering:
          - Golang: ./golang.md
          - Node: ./node.md
          - Shell: ./shell.md
      - Infrastructure/DevOps:
          - Docker: ./docker.md
          - Git: ./git.md
          - Gitlab CI: ./gitlab-ci.md
          - GPG Keys: ./gpg.md
          - Kubernetes: ./kubernetes.md
          - Nginx: ./nginx.md
          - Public Key Infrastructure: ./pki.md
          - VSCode/VSCodium: ./vscode.md
      - Operating Systems:
          - Ubuntu: ./code/os/ubuntu.md
      - Other Skills:
          - Typing: ./typing.md
  - Money: ./money.md
  - OD/Coaching/Counselling:
      - Interpersonal: ./od/interpersonal.md
      - Intrapersonal: ./od/intrapersonal.md
      - Psychological Safety: ./od/psychological-safety.md
  - Wing Chun: ./wingchun/index.md
  - Bahasa:
      - Colours: ./bahasa/colours.md
      - Feelings: ./bahasa/feelings.md
      - Locations: ./bahasa/locations.md
      - Numbers: ./bahasa/numbers.md
      - Titles: ./bahasa/titles.md
  - Español:
      - El Tiempo: ./español/el-tiempo.md
      - La Familia: ./español/la-familia.md
      - Numeros y Recuento: ./español/numeros-y-recuento.md
      - Países y Nacionalidades: ./español/países-y-nacionalidades.md
      - Referencias de Aprender: ./español/referencias-de-aprender.md
      - Verbos: ./español/verbos.md
      - Vocabulario: ./español/vocabulario.md
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - sh
    - golang
    - js
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
dev_addr: 0.0.0.0:12345
