site_name: wiki.joeir.net
site_url: http://wiki.joeir.net
repo_url: https://github.com/zephinzer/net.joeir.wiki.
site_author: zephinzer
site_description: my wiki of sorts
nav:
  - Home: ./index.md
  - Code Logistics:
    - Git 101: ./code-logistics/git.md
  - Wing Chun:
    - Forms: ./wing-chun/forms.md
  - Espa単ol:
    - Los Verbos: ./espa単ol/los-verbos.md
    - Los Numeros: ./espa単ol/los-numeros.md
    - El Tiempo: ./espa単ol/el-tiempo.md
theme: mkdocs
markdown_extensions:
  - admonition