apiVersion: v1
kind: Service
metadata:
  name: template
  labels:
    app: template
    type: service
spec:
  type: LoadBalancer
  selector:
    name: echoserver
    type: pod
  ports:
    - port: 11111
      protocol: TCP
      name: service-http
      targetPort: pod-http
