apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: template
spec:
  rules:
  - host: testing.local
    http:
      paths:
      - path: /
        backend:
          serviceName: template
          servicePort: 11111
